name: thewhiteroom
favicon: null
layout_spectrum: 0.09277820424176753
typography_spectrum: 0.8631173404864967
title: The White Room
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#fcfdff'
    - '#3d423e'
    - '#b1b7b7'
    - '#616860'
  brandStrength: 0.9601767573039979
  lightness: 0.6875
  saturation: 0.6434121616184711
  rhythmicContrast: 0.5906905073206872
purpose: []
